import { Prisma, PriceType } from '@prisma/client';
import { prisma } from './prisma';

const price = (value: PriceType) => value === 'FREE_TRIAL' ? 'Free Trial' : value.charAt(0) + value.slice(1).toLowerCase();
export class CatalogService {
  private tool(value: any) { const { category, affiliateNetwork, ...tool } = value; return { ...tool, categoryName: category?.name || 'Software', affiliateUrl: tool.affiliateUrl || tool.officialUrl, affiliateNetwork: affiliateNetwork?.name || 'Direct Partner', priceType: price(tool.priceType), freeTrialDays: tool.freeTrialDays || 0, faqs: tool.faqs || [], pricingTiers: tool.pricingTiers || [], createdAt: tool.createdAt?.toISOString?.() || tool.createdAt, updatedAt: tool.updatedAt?.toISOString?.() || tool.updatedAt }; }
  private category(value: any) { return { ...value, featuredToolsCount: value.tools?.filter((tool: any) => tool.isFeatured).length || 0, totalToolsCount: value._count?.tools || value.tools?.length || 0, tools: undefined }; }
  private deal(value: any) { return { ...value, toolName: value.tool?.name || 'Partner Tool', toolSlug: value.tool?.slug || '', toolLogo: value.tool?.logo || '', expiresAt: value.expiresAt.toISOString(), tool: undefined }; }
  async tools(query: Record<string, string>) {
    const where: Prisma.ToolWhereInput = { ...(query.featured === 'true' ? { isFeatured: true } : {}), ...(query.trending === 'true' ? { isTrending: true } : {}), ...(query.category ? { category: { slug: query.category } } : {}), ...(query.q ? { OR: ['name', 'tagline', 'description'].map(field => ({ [field]: { contains: query.q } })) } : {}) };
    const take = Math.min(Math.max(Number(query.limit || 50), 1), 100);
    const [items, total] = await prisma.$transaction([prisma.tool.findMany({ where, take, skip: Math.max(Number(query.offset || 0), 0), include: { category: true, affiliateNetwork: true }, orderBy: query.sortBy === 'rating' ? { rating: 'desc' } : query.sortBy === 'newest' ? { createdAt: 'desc' } : { viewsCount: 'desc' } }), prisma.tool.count({ where })]);
    return { tools: items.map(value => this.tool(value)), total };
  }
  async toolBySlug(slug: string) { const item = await prisma.tool.findUnique({ where: { slug }, include: { category: true, affiliateNetwork: true } }); if (!item) throw new Error('NOT_FOUND:Tool not found'); return this.tool(item); }
  async categories() { const values = await prisma.category.findMany({ include: { tools: { select: { isFeatured: true } }, _count: { select: { tools: true } } }, orderBy: { name: 'asc' } }); return values.map(value => this.category(value)); }
  async categoryBySlug(slug: string) { const item = await prisma.category.findUnique({ where: { slug }, include: { tools: { select: { isFeatured: true } }, _count: { select: { tools: true } } } }); if (!item) throw new Error('NOT_FOUND:Category not found'); return this.category(item); }
  async comparisons() { return prisma.comparison.findMany({ orderBy: { createdAt: 'desc' } }); }
  async comparison(slug: string) { const item = await prisma.comparison.findUnique({ where: { slug } }); if (!item) throw new Error('NOT_FOUND:Comparison not found'); return item; }
  async deals(query: Record<string, string>) { const values = await prisma.deal.findMany({ where: { ...(query.category ? { category: query.category } : {}), ...(query.verifiedOnly === 'true' ? { isVerified: true } : {}) }, include: { tool: true }, orderBy: { expiresAt: 'asc' } }); return values.map(value => this.deal(value)); }
  async guides() { const values = await prisma.guide.findMany({ orderBy: { publishedAt: 'desc' } }); return values.map(value => ({ ...value, publishedAt: value.publishedAt.toISOString(), updatedAt: value.updatedAt.toISOString() })); }
  async guide(slug: string) { const item = await prisma.guide.findUnique({ where: { slug } }); if (!item) throw new Error('NOT_FOUND:Guide not found'); return { ...item, publishedAt: item.publishedAt.toISOString(), updatedAt: item.updatedAt.toISOString() }; }
  async freeTools() { return prisma.freeTool.findMany({ orderBy: { name: 'asc' } }); }
  async freeTool(slug: string) { const item = await prisma.freeTool.findUnique({ where: { slug } }); if (!item) throw new Error('NOT_FOUND:Free tool not found'); return item; }
  async upvoteDeal(id: string) { return prisma.deal.update({ where: { id }, data: { upvotes: { increment: 1 } } }); }
  async search(q: string) { const query = q.trim(); if (!query) return { tools: [], categories: [], comparisons: [], deals: [], guides: [], freeTools: [] }; const [toolData, categories, comparisons, deals, guides, freeTools] = await Promise.all([this.tools({ q: query, limit: '8' }), prisma.category.findMany({ where: { OR: [{ name: { contains: query } }, { description: { contains: query } }] }, take: 6 }), prisma.comparison.findMany({ where: { OR: [{ title: { contains: query } }, { summary: { contains: query } }] }, take: 6 }), this.deals({}), prisma.guide.findMany({ where: { OR: [{ title: { contains: query } }, { excerpt: { contains: query } }] }, take: 6 }), prisma.freeTool.findMany({ where: { OR: [{ name: { contains: query } }, { description: { contains: query } }] }, take: 6 })]); return { tools: toolData.tools, categories: categories.map(value => this.category(value)), comparisons, deals: deals.filter(deal => `${deal.title} ${deal.toolName}`.toLowerCase().includes(query.toLowerCase())).slice(0, 6), guides, freeTools }; }
  async createTool(body: any) { const item = await prisma.tool.create({ data: { ...body, priceType: String(body.priceType || 'FREEMIUM').toUpperCase().replace(' ', '_') as PriceType, longReview: body.longReview || body.description, pricingTiers: body.pricingTiers || [], features: body.features || [], pros: body.pros || [], cons: body.cons || [], bestFor: body.bestFor || body.targetAudience || [], alternatives: body.alternatives || [], screenshots: body.screenshots || [], officialUrl: body.officialUrl, categoryId: body.categoryId }, include: { category: true, affiliateNetwork: true } }); return this.tool(item); }
}
export const catalog = new CatalogService();
